name: AutoGen Studio Docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: python/packages/autogen-studio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jianjungki/autogenstudio:latest
    
    - name: Check manifest
        run: docker buildx imagetools inspect jianjungki/autogenstudio:latest
